#!/bin/bash

CONTAINERS="$( docker ps -a | grep -v 'uifd/ui-for-docker' | grep -v 'CONTAINER ID' | awk '{ print $1 }' )"

if [[ -n "$CONTAINERS" ]] ; then
  echo 'stopping containers...'
  docker stop -t 5 $CONTAINERS | sed 's/^/ * /'
  echo 'deleting containers...'
  docker rm -f $CONTAINERS | sed 's/^/ * /'
else
  echo 'no containers to stop'
fi
