#!/usr/bin/env python3

#
# script for transforming adb output into series of clickable events with click timeouts.
# example usage:
# adb -s 192.168.57.101:5555 shell getevent -tl
#

import sys
import re

try:
  touchFound=False
  tapTime=None
  p = re.compile('\\[(\\d*)\\.\\d\\]*')
  for line in sys.stdin:
    if 'BTN_TOUCH' in line and 'DOWN' in line:
      t = int(p.match(line).group(1))
      if tapTime is None:
        print(str(1), end=" ")
      else:
        print(str(t - tapTime + 1), end=" ")
      tapTime = t
      touchFound=True
      continue
    if touchFound:
      if 'ABS_MT_POSITION_X' in line:
        print(int(line.split()[-1], 16), end=" ")
      if 'ABS_MT_POSITION_Y' in line:
        touchFound=False
        print(int(line.split()[-1], 16))
except KeyboardInterrupt:
  sys.exit(0)
