#!/bin/bash

set -e

#if [[ -n "$1" ]] ; then
#  readonly FNAME="$1"
#else
#  readonly FNAME="screen-$( date -u +'%Y%m%d-%H%M%S' ).png"
#fi

readonly FNAME="screen-$( date -u +'%Y%m%d-%H%M%S' ).png"
if [[ -s "$FNAME" ]] ; then
  rm -f "$FNAME"
fi

if [[ -n "$1" ]] ; then
  readonly DEVICE="-s 192.168.$1:5555"
else
  readonly DEVICE=""
fi

readonly ADB='/opt/genymobile/genymotion/tools/adb'
$ADB $DEVICE shell screencap -p "/sdcard/Download/$FNAME"
$ADB $DEVICE pull "/sdcard/Download/$FNAME"
$ADB $DEVICE shell rm "/sdcard/Download/$FNAME"
